### ISSUE TITLE
France bounds are wrong. 

### ISSUE THREAD

**Issue by renaudcerrato** [sandstrom/country-bounding-boxes#3]
![Screenshot_20231013-073720](https://github.com/sandstrom/country-bounding-boxes/assets/1930949/38e6f5b8-1b6e-48e5-be67-f07f8b793fe7)

**Comment by sandstrom** [comment]
If you can open a PR with a short explanation of what you think is wrong, and what you think the boundaries should be, I'll consider it.

**Comment by renaudcerrato** [comment]
Do you really need an explanation of what's wrong looking at the screenshot? That point is way out of the bounding box of France, if you ever know where the France is.

**Comment by sandstrom** [comment]
@renaudcerrato I know where France is, thank you! By writing a negative comment like that, you are not making it more likely that I will work on this.

This code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

So if you want something, a good first step is to explain in detail what you think should be changed, then open a PR with the necessary code changes.
